spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_account?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
